### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'reference_path'. Did you mean: 'references_path'?

### ISSUE THREAD

**Issue by bayraktar1** [marcpaga/nanopore_benchmark#5]
Hello @marcpaga,

When I try to run:

`python3 evaluate_referencegenome.py --basecalls-path mytest/mymodel --references-path mytest/myref.fa --model-name mymodel`

(myref.fa is a genome with chromosomes, not per read)

I get the following error:

```
Traceback (most recent call last):
  File "/linuxhome/tmp/dogukan/nanopore_benchmark/evaluate_referencegenome.py", line 144, in <module>
    multiple_results = [pool.apply_async(eval_pair_wrapper, (reads_queue, writer_queue, args.reference_path, args.homopolymer_length, args.verbose)) for _ in range(args.processes-1)]
  File "/linuxhome/tmp/dogukan/nanopore_benchmark/evaluate_referencegenome.py", line 144, in <listcomp>
    multiple_results = [pool.apply_async(eval_pair_wrapper, (reads_queue, writer_queue, args.reference_path, args.homopolymer_length, args.verbose)) for _ in range(args.processes-1)]
AttributeError: 'Namespace' object has no attribute 'reference_path'. Did you mean: 'references_path'?
Process Process-2:
Traceback (most recent call last):
  File "/home/dogukan/mambaforge/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/dogukan/mambaforge/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/linuxhome/tmp/dogukan/nanopore_benchmark/evaluate_referencegenome.py", line 17, in results_queue_writer
    df = q.get()
  File "<string>", line 2, in get
  File "/home/dogukan/mambaforge/lib/python3.10/multiprocessing/managers.py", line 818, in _callmethod
    kind, result = conn.recv()
  File "/home/dogukan/mambaforge/lib/python3.10/multiprocessing/connection.py", line 255, in recv
    buf = self._recv_bytes()
  File "/home/dogukan/mambaforge/lib/python3.10/multiprocessing/connection.py", line 419, in _recv_bytes
    buf = self._recv(4)
  File "/home/dogukan/mambaforge/lib/python3.10/multiprocessing/connection.py", line 388, in _recv
    raise EOFError
EOFError
```

Seems like an argparse error?

I tried changing line 144 as mentioned in the error from:
      
`multiple_results = [pool.apply_async(eval_pair_wrapper, (reads_queue, writer_queue, **args.reference_path**, args.homopolymer_length, args.verbose)) for _ in range(args.processes-1)]`

to

`multiple_results = [pool.apply_async(eval_pair_wrapper, (reads_queue, writer_queue, **args.references_path**, args.homopolymer_length, args.verbose)) for _ in range(args.processes-1)]`

but this caused a lot of different errors

Any ideas?

**Comment by marcpaga** [comment]
Thanks for spotting the argparse typo, this is indeed the cause of your first error. Can you share the following errors that you get?

**Comment by bayraktar1** [comment]
Here is the error I get after changing the typo and running the same command again:

```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/dogukan/mambaforge/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/linuxhome/tmp/dogukan/nanopore_benchmark/evaluate_referencegenome.py", line 60, in eval_pair_wrapper
    result = eval_pair(
  File "/linuxhome/tmp/dogukan/nanopore_benchmark/src/evaluation.py", line 325, in eval_pair
    len_ref = len(ref.seq(read_id))
TypeError: object of type 'NoneType' has no len()
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/linuxhome/tmp/dogukan/nanopore_benchmark/evaluate_referencegenome.py", line 145, in <module>
    results = [res.get() for res in multiple_results]
  File "/linuxhome/tmp/dogukan/nanopore_benchmark/evaluate_referencegenome.py", line 145, in <listcomp>
    results = [res.get() for res in multiple_results]
  File "/home/dogukan/mambaforge/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
TypeError: object of type 'NoneType' has no len()
Process Process-2:
Traceback (most recent call last):
  File "/home/dogukan/mambaforge/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/dogukan/mambaforge/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/linuxhome/tmp/dogukan/nanopore_benchmark/evaluate_referencegenome.py", line 17, in results_queue_writer
    df = q.get()
  File "<string>", line 2, in get
  File "/home/dogukan/mambaforge/lib/python3.10/multiprocessing/managers.py", line 818, in _callmethod
    kind, result = conn.recv()
  File "/home/dogukan/mambaforge/lib/python3.10/multiprocessing/connection.py", line 255, in recv
    buf = self._recv_bytes()
  File "/home/dogukan/mambaforge/lib/python3.10/multiprocessing/connection.py", line 419, in _recv_bytes
    buf = self._recv(4)
  File "/home/dogukan/mambaforge/lib/python3.10/multiprocessing/connection.py", line 388, in _recv
    raise EOFError
EOFError

```

**Comment by marcpaga** [comment]
There is an error in handling the reference sequencing when it comes from a genome, I have pushed a fix for it. I got it working on my end, can you test it please?

**Comment by bayraktar1** [comment]
The program has not finished running yet, but it seems to be working! It has been running for a couple of hours now, and I can see that new lines are continuously being written to the `evaluation.csv`. Thanks for the quick fix!

**Comment by bayraktar1** [comment]
It seems like I celebrated too soon... ☹️

I got a keyError:
```

/linuxhome/tmp/dogukan/nanopore_benchmark/venv3/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3440: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/linuxhome/tmp/dogukan/nanopore_benchmark/venv3/lib/python3.10/site-packages/numpy/core/_methods.py:189: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/linuxhome/tmp/dogukan/nanopore_benchmark/venv3/lib/python3.10/site-packages/numpy/core/_methods.py:262: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof, 
/linuxhome/tmp/dogukan/nanopore_benchmark/venv3/lib/python3.10/site-packages/numpy/core/_methods.py:222: RuntimeWarning: invalid value encountered in true_divide
  arrmean = um.true_divide(arrmean, div, out=arrmean, casting='unsafe',
/linuxhome/tmp/dogukan/nanopore_benchmark/venv3/lib/python3.10/site-packages/numpy/core/_methods.py:254: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
multiprocessing.pool.RemoteTraceback: 
"""                                                        
Traceback (most recent call last):
  File "/home/dogukan/mambaforge/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/linuxhome/tmp/dogukan/nanopore_benchmark/evaluate_referencegenome.py", line 60, in eval_pair_wrapper
    result = eval_pair(                                    
  File "/linuxhome/tmp/dogukan/nanopore_benchmark/src/evaluation.py", line 369, in eval_pair
    signatures = error_profile(local_arr)
  File "/linuxhome/tmp/dogukan/nanopore_benchmark/src/evaluation.py", line 197, in error_profile
    mut_dict[code] += 1                                    
KeyError: 'A->NT'                                          
"""                                                        

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/linuxhome/tmp/dogukan/nanopore_benchmark/evaluate_referencegenome.py", line 145, in <module>
    results = [res.get() for res in multiple_results]
  File "/linuxhome/tmp/dogukan/nanopore_benchmark/evaluate_referencegenome.py", line 145, in <listcomp>
    results = [res.get() for res in multiple_results]
  File "/home/dogukan/mambaforge/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value                                      
KeyError: 'A->NT'                                          
Process Process-2:                                         
Traceback (most recent call last):
  File "/home/dogukan/mambaforge/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()                                             
  File "/home/dogukan/mambaforge/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/linuxhome/tmp/dogukan/nanopore_benchmark/evaluate_referencegenome.py", line 17, in results_queue_writer
    df = q.get()                                           
  File "<string>", line 2, in get
  File "/home/dogukan/mambaforge/lib/python3.10/multiprocessing/managers.py", line 818, in _callmethod
    kind, result = conn.recv()
  File "/home/dogukan/mambaforge/lib/python3.10/multiprocessing/connection.py", line 255, in recv
    buf = self._recv_bytes()                               
  File "/home/dogukan/mambaforge/lib/python3.10/multiprocessing/connection.py", line 419, in _recv_bytes
    buf = self._recv(4)                                    
  File "/home/dogukan/mambaforge/lib/python3.10/multiprocessing/connection.py", line 388, in _recv
    raise EOFError                                         
EOFError
```

**Comment by marcpaga** [comment]
I did not consider N bases in the reference genome, therefore this error is raised. I have applied an update that will skip these bases from the analysis.

Reads with mapping to a reference with N bases in the alignment will be flagged with `nbases` in the `comment` column of the `evaluation.csv` file. If you want to completely skip those reads from subsequent analysis you have to filter those out from the file.

**Comment by bayraktar1** [comment]
Hi Marc,

The script finished successfully, but I ran into an error when trying to create a report from the `evaluation.csv` with the following command:

```
python3 report.py --evaluation-file mytest/mymodel/evaluation.csv --output-dir mytest/mymodel/reports
```

```
Output dir: /linuxhome/tmp/dogukan/nanopore_benchmark/mytest/mymodel/reports                                                                                   │
Traceback (most recent call last):                                                                                                                             │
  File "/linuxhome/tmp/dogukan/nanopore_benchmark/report.py", line 51, in <module>                                                                             │
    ereport.phredq_distributions()                                                                                                                             │
  File "/linuxhome/tmp/dogukan/nanopore_benchmark/src/report.py", line 264, in phredq_distributions                                                            │
    overlap = self.calculate_phredq_overlap(subdf)                                                                                                             │
  File "/linuxhome/tmp/dogukan/nanopore_benchmark/src/report.py", line 242, in calculate_phredq_overlap                                                        │
    mid_pos = findIntersection(funcA, funcB, np.mean(y), np.mean(x))                                                                                           │
  File "/linuxhome/tmp/dogukan/nanopore_benchmark/src/report.py", line 224, in findIntersection                                                                │
    return brentq(lambda x : fun1(x) - fun2(x), lower, upper)                                                                                                  │
  File "/linuxhome/tmp/dogukan/nanopore_benchmark/venv3/lib/python3.10/site-packages/scipy/optimize/zeros.py", line 776, in brentq                             │
    r = _zeros._brentq(f, a, b, xtol, rtol, maxiter, args, full_output, disp)                                                                                  │
ValueError: f(a) and f(b) must have different signs           
```

It also seems like the `scikit-learn` dependency is missing from the `requirements.txt`. I had to install it manually to the environment.

**Comment by marcpaga** [comment]
This seems to be a mathematical error, I am afraid I will need access to the data to be able to reproduce and debug this. Would that be possible? Or if you could make a minimal reproducible example that would also work.

**Comment by bayraktar1** [comment]
I can share the data with you. What would you need exactly? The evaluation.csv, genome fasta, model.fastq? Could I share a drive link with you through e-mail?

**Comment by marcpaga** [comment]
The evaluation.csv should suffice. Perhaps you can cut the file to something like 1000 lines, check if it fails, and if it does fail paste it here?

**Comment by bayraktar1** [comment]
Putting even a small part of the file in a comment exceeds the maximum character limit. So I put it in a GitHub gist instead: https://gist.github.com/bayraktar1/5ccae044aba77554126a45d8da13928c It contains the first 1000 lines of the `evaluation.csv`. I was able to recreate the error with this smaller file. You might need to download the file, for some reason the view on the webpage cuts off at line 695.

**Comment by marcpaga** [comment]
Thanks for the example file. I have pushed a fix that works with the data you provided. The problem was in some optimization parameters that were data derived.

**Comment by bayraktar1** [comment]
I ran the new version with the partial evaluation.csv I shared with you, and it worked. Before this change, it did not.

However, when running it on the full evaluation.csv, I receive the same error, unfortunately.

```
Output dir: /linuxhome/tmp/dogukan/nanopore_benchmark/mytest/mymodel/reportsaaaaa                                     │
Traceback (most recent call last):                                                                                    │
  File "/linuxhome/tmp/dogukan/nanopore_benchmark/report.py", line 51, in <module>                                    │
    ereport.phredq_distributions()                                                                                    │
  File "/linuxhome/tmp/dogukan/nanopore_benchmark/src/report.py", line 264, in phredq_distributions                   │
    overlap = self.calculate_phredq_overlap(subdf)                                                                    │
  File "/linuxhome/tmp/dogukan/nanopore_benchmark/src/report.py", line 242, in calculate_phredq_overlap               │
    mid_pos = findIntersection(funcA, funcB, 0, 60)                                                                   │
  File "/linuxhome/tmp/dogukan/nanopore_benchmark/src/report.py", line 224, in findIntersection                       │
    return brentq(lambda x : fun1(x) - fun2(x), lower, upper)                                                         │
  File "/linuxhome/tmp/dogukan/nanopore_benchmark/venv3/lib/python3.10/site-packages/scipy/optimize/zeros.py", line 77│
6, in brentq                                                                                                          │
    r = _zeros._brentq(f, a, b, xtol, rtol, maxiter, args, full_output, disp)                                         │
ValueError: f(a) and f(b) must have different signs
```

I arbitrarily changed the value of the following line from the fix that you pushed:
```
mid_pos = findIntersection(funcA, funcB, 0, 60), error
mid_pos = findIntersection(funcA, funcB, 0, 70), error
mid_pos = findIntersection(funcA, funcB, 0, 80), error
mid_pos = findIntersection(funcA, funcB, 0, 90), worked
mid_pos = findIntersection(funcA, funcB, 0, 120), worked
```
The report script ran successfully on the full `evaluation.csv` with a value of 90 and 120

**Comment by marcpaga** [comment]
Thanks for testing other range values, you must have some really high PhredQ scores then. I wrongly assumed that 60 would be the max. Did runtime increase a lot by using higher values? If not I will set it to 120 as well.

**Comment by bayraktar1** [comment]
There does not seem to be a time difference between 90 and 120.
My `evaluation.csv` has, 301481 lines. About 377MB

60, 70, 80: error after 1 min
90: ~1 hour 20 min
120: ~1 hour 20 min

**Comment by marcpaga** [comment]
Thanks for the benchmark. If there are no more issues, feel free to close the issue.

**Comment by bayraktar1** [comment]
I successfully ran plot.py for two models, closing this issue.
